services:
  superset:
    restart: no
    ports:
      - ${SUPERSET_PORT:-8088}:8088

  database:
    restart: no
    platform: linux/amd64 # Pour compatibilité si nécessaire
    ports:
      - 5432:5432