services:
  superset:
    restart: no
    ports:
      - ${SUPERSET_PORT:-8088}:8088

  database:
    restart: no
    platform: linux/amd64 # Pour compatibilité si nécessaire
    ports:
      - 5432:5432

  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    container_name: ${MAIN_CONTAINER_NAME:-superset}_tailscale
    hostname: ${MAIN_CONTAINER_NAME:-superset-postgres}
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${DATA_PATH:-./appData}/tailscale:/var/lib/tailscale
    networks:
      - superset
    depends_on:
      - database
  postgres-proxy:
    image: alpine/socat:latest
    restart: unless-stopped
    container_name: ${MAIN_CONTAINER_NAME:-superset}_postgres_proxy
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:database:5432
    networks:
      - superset
      - tailscale
    depends_on:
      - database
      - tailscale

networks:
  tailscale:
    name: ${BACKEND_NETWORK}_tailscale
    driver: bridge